version: '3.8'
services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: dcm
      POSTGRES_USER: dcm_user
      POSTGRES_PASSWORD: dcm_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-data.sql:/docker-entrypoint-initdb.d/init-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dcm_user -d dcm"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    image: dcm-app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dcm
      SPRING_DATASOURCE_USERNAME: dcm_user
      SPRING_DATASOURCE_PASSWORD: dcm_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    restart: on-failure
#credentials should not be hardcoded in production, but for the sake of testing i went with that approach
volumes:
  postgres_data: